### ISSUE TITLE
Interacts in steam browser

### ISSUE THREAD

**Issue by riley805** [riley805/BTG_IssueTracker#36]
ISSUE SUBMITTED ON BEHALF OF: DILF (2852)

dropdown menus in interacts while in steam browser are messed up, they appear skewed. for longer dropdown menus this can make it so you can't read the items lower in the list

**Comment by LunavisM** [comment]
Steam browser does not support certain elements of the website, If you need to use interacts it is recommended to use your normal browser outside of the game. 
This will not be fixed
