### ISSUE TITLE
Hours Wiped

### ISSUE THREAD

**Issue by riley805** [riley805/BTG_IssueTracker#37]
This issue was created in-game by Legatus (76561198252522002)

Joined server on new IP.

My hours are wiped and I cant get them, restarted to 0, now up to 91 hours as of report

Previously held 387 hours at last memory

**Comment by sunshoes** [comment]
Not a bug; all old accounts were pruned. For details, including how to recover lost hours, see [this link](https://playbtg.com/threads/account-transfers-into-new-system.5725/).
