### ISSUE TITLE
Crashing when clicking close on motd

### ISSUE THREAD

**Issue by riley805** [riley805/BTG_IssueTracker#41]
This issue was created in-game by Teh player (76561198355819006)

I am in the chromium branch and when clicking close on the motd my game will crash shortly after. It only happens when i am loading in and i click close before i hear the water drowing noise meaning ive connected.

**Comment by LunavisM** [comment]
Chromium is not the main branch of GMod and therefore this issue cannot be fixed by us as it is a game related and not a server related issue. Switch to the regular branch to fix this issue.
