### ISSUE TITLE
I am getting slain for killing people correctly

### ISSUE THREAD

**Issue by riley805** [riley805/BTG_IssueTracker#45]
This issue was created in-game by K1llerNarwhal (76561198042255231)

Quite frankly there was a rediculous amount of evidence to suggest I was killing t's and I am getting slain for no reason. Literally this guy was magneto sticking an unidentified body, and on almost every server not id'ing a body is a t act. Also, another dude was badly wounded and disposing of an unidentified body. I thought it was a detectives job to try and kill t's. If killing based on overwhelming suspicion is unjustified, then the t's have a massive advantage that is almost insurmountable

**Comment by LunavisM** [comment]
This is for bug reporting. If you have a complaint about a staff member or
donator slaying you incorrectly please make a staff report on the forums.
