### ISSUE TITLE
Reaper Gun didn't kill victim

### ISSUE THREAD

**Issue by riley805** [riley805/BTG_IssueTracker#47]
ISSUE SUBMITTED ON BEHALF OF: Tori (4614)

I used a reaper gun on the last inno. gloated about having won. The victim straight up didn't die, only took 72 damage, and killed me in my confused stupor. I'd like to report this karmic retribution for destroying my ego

https://steamcommunity.com/sharedfiles/filedetails/?id=1842406035

I have no idea how to recreate this as this happened only once

**Comment by LunavisM** [comment]
SemiVanilla is gone
